# GitHub Actions workflow para CI/CD do DebugAI
# Este workflow instala dependências, executa testes e faz build do Docker
# Além disso, executa Terraform plan automaticamente e Terraform apply apenas após aprovação

name: CI/CD DebugAI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          pytest test_main.py -v

      - name: Build Docker image
        run: |
          docker build -t debugai .

  terraform-plan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init Terraform
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          TF_VAR_gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
        run: terraform -chdir=terraform plan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment:
      name: production   # 🔒 exige aprovação manual antes de aplicar
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init Terraform
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          TF_VAR_gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
        run: terraform -chdir=terraform apply -auto-approve
