# GitHub Actions workflow para CI/CD do DebugAI
# Este workflow instala dependências, executa testes e faz build do Docker
# Você pode expandir para deploy automático na AWS ou outros serviços

name: CI/CD DebugAI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes (adicione seus testes aqui)
        run: |
          echo "Nenhum teste definido ainda. Adicione testes em test_*.py."

      - name: Build Docker image
        run: |
          docker build -t debugai .


  terraform:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Inicializar Terraform
        run: terraform -chdir=terraform init

      - name: Validar Terraform
        run: terraform -chdir=terraform validate

      - name: Debug AWS secrets (temporário)
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY length: ${#AWS_SECRET_ACCESS_KEY}"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Aplicar Terraform (apenas para testes, não produção)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: terraform -chdir=terraform plan
        # Para aplicar de verdade, troque 'plan' por 'apply -auto-approve'
